- id: '1582197301380'
  alias: Tænd LED båndet om natten
  description: ''
  trigger:
  - device_id: 82e4ee243fff4fe5aae77fcb46495396
    domain: binary_sensor
    entity_id: binary_sensor.repo_sensor_motion
    for:
      hours: 0
      minutes: 0
      seconds: 1
    platform: device
    type: motion
  condition:
  - after: '22:00'
    before: '07:00'
    condition: time
  action:
  - data:
      group_name: Køkken
      scene_name: Dæmpet
    service: hue.hue_activate_scene
  - delay: 00:10:00
  - entity_id: light.led_bandet
    service: light.turn_off
- id: '1582412646897'
  alias: Goodmorning
  description: ''
  trigger:
  - at: 08:30
    platform: time
  condition: []
  action:
  - data:
      volume_level: 0.05
    entity_id: media_player.sovevaerelset
    service: media_player.volume_set
  - data:
      entity_id: media_player.sovevaerelset
      uri: spotify:track:5ewowUOD4MOXDiOBRu7pMh
    service: spotcast.start
  - scene: scene.wakeup
  - data:
      volume_level: 0.1
    entity_id: media_player.sovevaerelset
    service: media_player.volume_set
  - delay: 00:00:20
  - data:
      volume_level: 0.15
    entity_id: media_player.sovevaerelset
    service: media_player.volume_set
  - delay: 00:00:12
  - data:
      volume_level: 0.2
    entity_id: media_player.sovevaerelset
    service: media_player.volume_set
  - delay: 00:00:12
  - data:
      volume_level: 0.3
    entity_id: media_player.sovevaerelset
    service: media_player.volume_set
  - delay: 00:00:12
  - data:
      volume_level: 0.4
    entity_id: media_player.sovevaerelset
    service: media_player.volume_set
