# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
    themes: !include themes.yaml
# Show the introduction message on startup.
#introduction:

# If you are using SSL/TLS, running in Docker container, etc.
http:
    base_url: https://hassio.dkjerkegaard.dk:8123
    ssl_certificate: /ssl/fullchain.pem
    ssl_key: /ssl/privkey.pem
    ip_ban_enabled: true
    login_attempts_threshold: 5

spotcast:
  username: !secret spotify_username
  password: !secret spotify_password

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

#konfigurationsfiler
switch: !include switches.yaml
scene: !include scenes.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
